version: '3.8'

x-environment: &default-environment
  MINIO_ACCESS_KEY: bdwsdjHtOmZEVvsbmJzo
  MINIO_SECRET_KEY: fpXu2UgNuRyE7gIKhtQCXg5J0Xg9zuq4PZzsmqoa
  MINIO_ENDPOINT_URL: "https://files.ryazan-market.ru"
  MINIO_PUBLIC_URL: "https://files.ryazan-market.ru"

services:
  s3_worker:
    build: .
    container_name: s3_worker
    environment:
      <<: [ *default-environment ]
    ports:
      - "8123:8000"
  api_s3:
    image: minio/minio:RELEASE.2024-05-01T01-11-10Z
    command: server /data --console-address ":9001"
    ports:
      - "9002:9000"
      - "9001:9001"
    environment:
      MINIO_ROOT_USER: minioadmin
      MINIO_ROOT_PASSWORD: minioadmin
    volumes:
      - s3-data_volume:/data


volumes:
  s3-data_volume:
